service: myTestService
provider:
  name: aws
  runtime: go1.x
  region: us-east-1
package:
  exclude:
    - ./**
  include:
    - ./bin/**
functions:
  hello:
    handler: bin/hello
  api:
    handler: bin/api
    events:
      - http:
          path: /products
          method: get
      - http:
          path: /categories
          method: get
      - http:
          path: /ping
          method: get
